project:
  type: website
  output-dir: docs
  
website:
  title: "Duncan Espenshade"
  sidebar:
    title: "Duncan Espenshade"
    style: "docked"
    logo: images/espenshade_headshot.jpg
    search: false
    contents:
      - href: overview.qmd
        text: "Home"
      - href: travel_info.qmd
      - href: teaching.qmd
      - href: cv.qmd
      - href: research.qmd
format:
  html:
    css: style.css
    page-layout: full
    
    
editor: source

