project:
  type: website
  output-dir: docs
  
website:
  title: "Duncan Espenshade"
  navbar:
    logo: images/espenshade_headshot.jpg
    search: false
    left:
      - href: overview.qmd
        text: "Home"
      - href: overview2.qmg
        text: "Home 2"
      - href: teaching.qmd
        text: "Teaching"
      - href: cv.qmd
      - href: research.qmd
      - href: contact.qmd
        text: "Contact Information"
format:
  html:
    css: style.css
    page-layout: full
    
    
editor: source

