project:
  type: website
  output-dir: docs
  
website:
  title: "Duncan Espenshade"
  navbar:
    logo: images/espenshade_headshot.jpg
    search: false
    left:
      - href: index.qmd
        text: "Home"
      - href: teaching.qmd
        text: "Teaching"
      - href: cv.qmd
      - href: research.qmd
      - href: contact.qmd
        text: "Contact Information"
format:
  html:
    css: style.css
    page-layout: article
    
    
editor: source

